feeds:
  - name: "Out"
    topic: "/sensmon/outnode/temp"
    delay: 5

  - name: "In"
    topic: "/sensmon/artekroom/temp"
    delay: 5
  
settings:
  matrix:
    - brightness: 5
    - dimmer:
      - brightness: 2
      - hour_from: 22
      - hour_to: 6
  mqtt:
    - brokerIP: 192.168.88.245
    - brokerPort: 1883
  http:
    - port: 8888
  clock:
    - format: '%h:%m:%s'